services:
  ibis-server:
    image: ghcr.io/canner/analytics-engine-ibis:latest
    ports:
      - "8000:8000"
    environment:
      ANALYTICS_ENGINE_ENDPOINT: http://java-engine:8080
  java-engine:
    image: ghcr.io/canner/analytics-engine:latest
    ports:
      - "8080:8080"
    volumes:
      - ./etc:/usr/src/app/etc
