version: '3.8'

services:
  engine:
    image: ghcr.io/canner/analytics-engine:latest
    platform: ${PLATFORM}
    ports:
      - 8080:8080
    volumes:
      - ./etc:/usr/src/app/etc
      - ./data:/usr/src/app/data
